USE ROLE INGESTION_LAB_ADMIN_ROLE;
USE DATABASE INGESTION_LAB_DB;
USE SCHEMA INGESTION;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV_STANDARD
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    COMMENT = 'Standard CSV file format for ingestion lab';

SHOW FILE FORMATS IN SCHEMA INGESTION_LAB_DB.INGESTION;