USE ROLE INGESTION_LAB_ADMIN_ROLE;
USE DATABASE INGESTION_LAB_DB;
USE SCHEMA INGESTION;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON_STANDARD
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE
    COMMENT = 'Standard JSON file format for ingestion lab';

SHOW FILE FORMATS IN SCHEMA INGESTION_LAB_DB.INGESTION;