use role INGESTION_LAB_DEVELOPER_ROLE;
use warehouse INGESTION_LAB_WH;
use database INGESTION_LAB_DB;

SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('INGESTION.TSK_UPDATE_LANDING_TABLES_START');
ALTER TASK INGESTION.tsk_update_landing_tables_start RESUME;
