use role INGESTION_LAB_DEVELOPER_ROLE;
use warehouse INGESTION_LAB_WH;
use database INGESTION_LAB_DB;

/*ALTER TASK ingestion.TSK_PROCESS_CUSTOMERS SUSPEND;
ALTER TASK ingestion.TSK_PROCESS_ORDERS SUSPEND;
ALTER TASK ingestion.TSK_PROCESS_ORDER_ITEMS SUSPEND;
ALTER TASK ingestion.TSK_PROCESS_PAYMENTS SUSPEND;
ALTER TASK ingestion.TSK_PROCESS_WEB_EVENTS SUSPEND;
ALTER TASK ingestion.TSK_PROCESS_SUPPORT_TICKETS SUSPEND;*/

ALTER TASK INGESTION.TSK_UPDATE_LANDING_TABLES_START SUSPEND;
