USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS INGESTION_LAB_ADMIN_ROLE
    COMMENT = 'Admin role for ingestion lab project';

CREATE ROLE IF NOT EXISTS INGESTION_LAB_DEVELOPER_ROLE
    COMMENT = 'Developer role for ingestion lab SQL development';

CREATE ROLE IF NOT EXISTS INGESTION_LAB_LOADER_ROLE
    COMMENT = 'Runtime loader role for ingestion jobs';

CREATE ROLE IF NOT EXISTS INGESTION_LAB_ANALYST_ROLE
    COMMENT = 'Read-only analyst role for curated data';


GRANT ROLE INGESTION_LAB_ANALYST_ROLE TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT ROLE INGESTION_LAB_LOADER_ROLE TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT ROLE INGESTION_LAB_DEVELOPER_ROLE TO ROLE INGESTION_LAB_ADMIN_ROLE;

GRANT ROLE INGESTION_LAB_ADMIN_ROLE TO ROLE SYSADMIN;