Use Role SysAdmin;

/* Privilege to role - INGESTION_LAB_ADMIN_ROLE*/
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE INGESTION_LAB_ADMIN_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE INGESTION_LAB_ADMIN_ROLE;

Use Role AccountAdmin;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE INGESTION_LAB_ADMIN_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE INGESTION_LAB_ADMIN_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE INGESTION_LAB_ADMIN_ROLE;

/* Privilege to role - INGESTION_LAB_ADMIN_ROLE - end */

SHOW GRANTS TO ROLE INGESTION_LAB_ADMIN_ROLE;
