USE ROLE INGESTION_LAB_ADMIN_ROLE;

CREATE WAREHOUSE IF NOT EXISTS INGESTION_LAB_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for ingestion lab SQL execution';