USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS INGESTION_LAB_ADMIN_USER
    PASSWORD = 'Sachin12345678'
    DEFAULT_ROLE = INGESTION_LAB_ADMIN_ROLE
    DEFAULT_WAREHOUSE = INGESTION_LAB_WH
    MUST_CHANGE_PASSWORD = FALSE;


CREATE USER IF NOT EXISTS INGESTION_LAB_DEVELOPER_USER
    PASSWORD = 'Sachin12345678'
    DEFAULT_ROLE = INGESTION_LAB_DEVELOPER_ROLE
    DEFAULT_WAREHOUSE = INGESTION_LAB_WH
    MUST_CHANGE_PASSWORD = FALSE;


CREATE USER IF NOT EXISTS INGESTION_LAB_LOADER_USER
    PASSWORD = 'Sachin12345678'
    DEFAULT_ROLE = INGESTION_LAB_LOADER_ROLE
    DEFAULT_WAREHOUSE = INGESTION_LAB_WH
    MUST_CHANGE_PASSWORD = FALSE;


CREATE USER IF NOT EXISTS INGESTION_LAB_ANALYST_USER
    PASSWORD = 'Sachin12345678'
    DEFAULT_ROLE = INGESTION_LAB_ANALYST_ROLE
    DEFAULT_WAREHOUSE = INGESTION_LAB_WH
    MUST_CHANGE_PASSWORD = FALSE;


USE ROLE SECURITYADMIN;

GRANT ROLE INGESTION_LAB_ADMIN_ROLE TO USER INGESTION_LAB_ADMIN_USER;
GRANT ROLE INGESTION_LAB_DEVELOPER_ROLE TO USER INGESTION_LAB_DEVELOPER_USER;
GRANT ROLE INGESTION_LAB_LOADER_ROLE TO USER INGESTION_LAB_LOADER_USER;
GRANT ROLE INGESTION_LAB_ANALYST_ROLE TO USER INGESTION_LAB_ANALYST_USER;
