Use Role INGESTION_LAB_ADMIN_ROLE;

/* Privileges to role - INGESTION_LAB_DEVELOPER_ROLE */
GRANT USAGE ON WAREHOUSE INGESTION_LAB_WH TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT USAGE ON DATABASE INGESTION_LAB_DB TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT USAGE ON SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;


GRANT CREATE TABLE ON SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT CREATE VIEW ON SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT CREATE TABLE ON SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT CREATE VIEW ON SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT CREATE TABLE ON SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT CREATE VIEW ON SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT SELECT ON ALL Views IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON ALL Views IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON ALL Views IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT SELECT ON FUTURE Views IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON FUTURE Views IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT SELECT ON FUTURE Views IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT CREATE STREAM ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT CREATE PIPE ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT CREATE FILE FORMAT ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT CREATE STAGE ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

GRANT CREATE TASK ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_DEVELOPER_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE INGESTION_LAB_DEVELOPER_ROLE;

/* Privileges to role - INGESTION_LAB_DEVELOPER_ROLE - end */

------------------------------------------------------------------------------------------------------------------------

/* Privileges to role - INGESTION_LAB_LOADER_ROLE */

GRANT USAGE ON WAREHOUSE INGESTION_LAB_WH TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT USAGE ON DATABASE INGESTION_LAB_DB TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT USAGE ON SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT USAGE ON SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT USAGE ON SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA INGESTION_LAB_DB.INGESTION TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT INSERT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT INSERT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.RAW TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT INSERT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_LOADER_ROLE;

GRANT INSERT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_LOADER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.AUDIT TO ROLE INGESTION_LAB_LOADER_ROLE;

/* GRANT EXECUTE TASK ON ACCOUNT TO ROLE INGESTION_LAB_LOADER_ROLE; */

/* Privileges to role - INGESTION_LAB_LOADER_ROLE - end */

------------------------------------------------------------------------------------------------------------------------


/* Privileges to role - INGESTION_LAB_ANALYST_ROLE */

GRANT USAGE ON WAREHOUSE INGESTION_LAB_WH TO ROLE INGESTION_LAB_ANALYST_ROLE;

GRANT USAGE ON DATABASE INGESTION_LAB_DB TO ROLE INGESTION_LAB_ANALYST_ROLE;

GRANT USAGE ON SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_ANALYST_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_ANALYST_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INGESTION_LAB_DB.CURATED TO ROLE INGESTION_LAB_ANALYST_ROLE;

/* Privileges to role - INGESTION_LAB_ANALYST_ROLE - end */



