USE ROLE INGESTION_LAB_ADMIN_ROLE;
use warehouse INGESTION_LAB_WH;
USE DATABASE INGESTION_LAB_DB;
USE SCHEMA INGESTION;

CREATE STAGE IF NOT EXISTS STG_S3_INGESTION_LAB
    URL = 's3://snowflake-ingestion-lab/'
    STORAGE_INTEGRATION = INT_AWS_S3_INGESTION_LAB
    COMMENT = 'External stage for AWS S3 ingestion lab files';

SHOW STAGES IN SCHEMA INGESTION_LAB_DB.INGESTION;