use role INGESTION_LAB_DEVELOPER_ROLE;
use warehouse INGESTION_LAB_WH;
use database INGESTION_LAB_DB;

SELECT 'RAW_CUSTOMERS_STREAM' AS stream_name,
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_CUSTOMERS_STREAM') AS has_data,
       (SELECT COUNT(*) FROM INGESTION.RAW_CUSTOMERS_STREAM) AS row_count
UNION ALL
SELECT 'RAW_ORDERS_STREAM',
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_ORDERS_STREAM'),
       (SELECT COUNT(*) FROM INGESTION.RAW_ORDERS_STREAM)
UNION ALL
SELECT 'RAW_ORDER_ITEMS_STREAM',
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_ORDER_ITEMS_STREAM'),
       (SELECT COUNT(*) FROM INGESTION.RAW_ORDER_ITEMS_STREAM)
UNION ALL
SELECT 'RAW_PAYMENTS_STREAM',
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_PAYMENTS_STREAM'),
       (SELECT COUNT(*) FROM INGESTION.RAW_PAYMENTS_STREAM)
UNION ALL
SELECT 'RAW_WEB_EVENTS_STREAM',
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_WEB_EVENTS_STREAM'),
       (SELECT COUNT(*) FROM INGESTION.RAW_WEB_EVENTS_STREAM)
UNION ALL
SELECT 'RAW_SUPPORT_TICKETS_STREAM',
       SYSTEM$STREAM_HAS_DATA('INGESTION_LAB_DB.INGESTION.RAW_SUPPORT_TICKETS_STREAM'),
       (SELECT COUNT(*) FROM INGESTION.RAW_SUPPORT_TICKETS_STREAM);